"""add estimated hours to roadmap tasks

Revision ID: 53ffaa426a90
Revises: adc27e9b34bd
Create Date: 2026-08-15 17:33:39.014862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ffaa426a90'
down_revision: Union[str, Sequence[str], None] = 'adc27e9b34bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmap_tasks', sa.Column('estimated_hours', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmap_tasks', 'estimated_hours')
    # ### end Alembic commands ###
